apiVersion: v1
kind: Namespace
metadata:
  name: pharmacy

---
apiVersion: v1
kind: Secret
metadata:
  name: pharmacy-db-secret
  namespace: pharmacy
type: Opaque
stringData:
  DB_HOST: "pharmacy-db.c7qim6s6ogkd.ap-south-1.rds.amazonaws.com"
  DB_USER: "admin"
  DB_PASS: "gufran2003"
  DB_NAME: "pharmacy_mgmt"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pharmacy-app
  namespace: pharmacy
  labels:
    app: pharmacy-app
spec:
  replicas: 1

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0   # 🔥 old pod tab tak delete nahi hoga jab tak new ready nahi

  selector:
    matchLabels:
      app: pharmacy-app

  template:
    metadata:
      labels:
        app: pharmacy-app

    spec:
      containers:
      - name: pharmacy

        # 🔥 IMPORTANT — Jenkins isko override karega
        image: PLACEHOLDER

        imagePullPolicy: Always

        ports:
        - containerPort: 80

        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: pharmacy-db-secret
              key: DB_HOST
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: pharmacy-db-secret
              key: DB_USER
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: pharmacy-db-secret
              key: DB_PASS
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: pharmacy-db-secret
              key: DB_NAME

        # 🔥 health checks (pipeline fail fix)
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 6

        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10