apiVersion: v1
kind: Namespace
metadata:
  name: pharmacy

---
apiVersion: v1
kind: Secret
metadata:
  name: pharmacy-db-secret
  namespace: pharmacy
type: Opaque
stringData:
  DB_HOST: "pharmacy-db.c7qim6s6ogkd.ap-south-1.rds.amazonaws.com"
  DB_USER: "admin"
  DB_PASS: "gufran2003"
  DB_NAME: "pharmacy_mgmt"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pharmacy-app
  namespace: pharmacy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pharmacy
  template:
    metadata:
      labels:
        app: pharmacy
    spec:
      containers:
      - name: pharmacy
        image: 062000001375.dkr.ecr.ap-south-1.amazonaws.com/pharmacy-app-repo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: pharmacy-db-secret
              key: DB_HOST
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: pharmacy-db-secret
              key: DB_USER
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: pharmacy-db-secret
              key: DB_PASS
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: pharmacy-db-secret
              key: DB_NAME
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15